config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :posts do
    resources :comments
  end

root 'posts#index'
get 'usuarios/sign_out(:usuario)' => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :usuario
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :usuario
	has_many :comments
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.usuario_id = current_usuario.id if current_usuario
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]

  respond_to :html

  def index
    @posts = Post.all.order("created_at DESC")
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = current_usuario.posts.build
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = current_usuario.posts.build(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:titulo, :contenido)
    end
end

app/controllers/usuario/confirmations_controller.rb
class Usuario::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/usuario/omniauth_callbacks_controller.rb
class Usuario::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/usuario/passwords_controller.rb
class Usuario::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/usuario/registrations_controller.rb
class Usuario::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/usuario/sessions_controller.rb
class Usuario::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
  layout false
  
end

app/controllers/usuario/unlocks_controller.rb
class Usuario::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
		<%= comment.comment%>
		<%= comment.usuario_id %>

		<%= link_to "Edit", edit_post_comment_path(comment.post, comment)%>
		<%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }%>
		<br>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

 <div class="field">
    <%= f.label :comentario %>
    <%= f.text_area :comment%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foroieee!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-default navbar-static-top" role="navigation">

<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-06">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="#">Foro IEEE!</a>
  </div>
  <div class="collapse navbar-collapse navbar-right" id="navbar-collapse-04" style="padding-right: 10px">
    <% if usuario_signed_in? %>
        <%= link_to 'Nuevo Post', new_post_path, :class=>"btn btn-default navbar-btn btn-sm", :type=>"button"%> 
        <%= link_to 'Cerrar Sesion', destroy_usuario_session_path, method: :delete, :class=>"btn btn-danger navbar-btn btn-sm", :type=>"button"%>

  <% else %>

         <%= link_to 'Registrarse' , new_usuario_registration_path,class: "btn btn-default navbar-btn btn-sm", type: "button", "data-toggle" => "modal", "data-target" => "#loginModal" %>
        

         <%= link_to 'Iniciar Sesion' , new_usuario_session_path, class: "btn btn-default navbar-btn btn-sm", type: "button" , "data-toggle" => "modal", "data-target" => "#loginModal"%>
  <% end %>
      

  

</nav>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Login</h4>
            </div>

            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
              
            </div>
        </div>
    </div>
</div>

  
 

<%= yield %>




<footer >


</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Foro</h1>



  <div class="row"> 
    <div class="col-md-8 col-md-offset-2" >
      <table class= "table">
        
         <thead>
            <tr>
              <th>Titulo</th>
              <th></th>
            <tr>  
         </thead>
         <tbody>
    <% @posts.each do |post| %>
       <tr>
      <td>
        <h4> <%= link_to post.titulo, post %> </h4>
        Publicado por
        <%= post.usuario.email %> ,<%= time_ago_in_words(post.created_at)%>
       
        
      </td>
      <td>
        <%= link_to 'Edit', edit_post_path(post), :type=>"button", :class=>"btn btn-link"%>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'}, type:"button", :class=>"btn btn-link" %>
      </td>
      <td>
        
      </td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>


<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-1" style="background:#80BFFF" >
	  <h3><%= @post.titulo %></h3>
	  <div class="col-md-3">
	  	
	  	<%= @post.usuario.email %>

  	  </div>
  	  <div class="col-md-6">
  	  	<strong>Contenido:</strong>
  	  	<%= @post.contenido %>
  	  </div>
  	 </div>
		<% #comments %>
	<div class="col-md-9 col-md-offset-1" style="background:#80BFFF" >
	 	<p><%= render @post.comments %></p>
 	</div>

</div>

 <h2>Reply</h2>
 <%= render "comments/form" %>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %> 
<%= link_to 'Destroy', post_path(@post), method: :delete, data: {confirm: "are you sure?"}%>